### ISSUE TITLE
Именования boolean переменных

### ISSUE THREAD

**Issue by humb1t** [akimov1995/io#4]
https://github.com/akimov1995/io/blob/b46c390f798ca0802a97916461b576cfb9fb16b1/src/main/java/xml/domParser/DomParser.java#L18

мне потребовалось время чтобы понять значения имён флагов.
Лучше использовать isЧтоТоТам нотацию и не стоит называть их flag

**Comment by akimov1995** [comment]
я менял название переменных

**Comment by humb1t** [comment]
принято
