### ISSUE TITLE
Ненужная переменная 

### ISSUE THREAD

**Issue by humb1t** [akimov1995/io#5]
https://github.com/akimov1995/io/blob/b46c390f798ca0802a97916461b576cfb9fb16b1/src/main/java/xml/saxParser/SaxParserHandler.java#L16

мы можем просто вставить условие во второй if - зачем дополнительная переменная?

**Comment by akimov1995** [comment]
Поправил issues, кроме последних 2, там не очень понял, нужно выполнить рефакторинг кода? в тот раз я спрашивал про него

**Comment by humb1t** [comment]
Принято
